name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Lint code with ESLint
        run: npx eslint . --ext .js


      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Give execute permissions to mocha
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run unit tests
        run: npm test
