name: CI con Docker y Pruebas

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas con npx
        run: npx mocha

      - name: Calcular cobertura
        run: |
          npx nyc npx mocha
          npx nyc report --reporter=text

      - name: Construir imagen Docker
        run: docker build -t mi-app .

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Subir imagen a Docker Hub
        run: docker push mi-app
