name: CI/CD Node App with Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test

    - name: Calcular cobertura
      run: |
        npx nyc npm test
        npx nyc report --reporter=text

    - name: Construir imagen Docker
      run: docker build -t mi-app .

    - name: Iniciar sesión en Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Etiquetar y subir imagen
      run: |
        docker tag mi-app ${{ secrets.DOCKER_USERNAME }}/mi-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mi-app:latest
