name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Give execute permissions to mocha
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run unit tests
        run: npm test

      - name: Docker build (manual)
        run: docker build -t app:latest .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker bake (using docker-bake.hcl)
        run: docker buildx bake --file docker-bake.hcl
